from typing import Protocol, Optional, Iterable
from .entities import UserEntity

class UserRepositoryPort(Protocol):
    def create(self, *, name: str, email: str, password_hash: str, role: str) -> UserEntity: ...
    def create_supplier_and_assign(self, *, name: str, email: str, password_hash: str, grocery_uid: str) -> UserEntity: ...
    def get_by_id(self, user_id: str) -> Optional[UserEntity]: ...
    def get_by_email(self, email: str) -> Optional[UserEntity]: ...
    def list(self) -> Iterable[UserEntity]: ...
    def update(self, user_id: str, **fields) -> UserEntity: ...
    def soft_delete(self, user_id: str) -> None: ...
